### ISSUE TITLE
Support soft deletion of an account

### ISSUE THREAD

**Issue by JKFSOM** [supabase/auth-py#375]
# Feature request

## Is your feature request related to a problem? Please describe.

This package is missing the option to soft delete an account. It's [present in gotrue](https://github.com/supabase/gotrue/blob/3991bdb269f72756becfacee5bd9e540c5b71250/internal/models/user.go#L709-L763) ([PR](https://github.com/supabase/gotrue-js/pull/587)), and can be [found in gotrue-js](https://github.com/supabase/gotrue-js/blob/c9296bbc27a2f036af55c1f33fca5930704bd021/src/GoTrueAdminApi.ts#L268C1-L284).

## Describe the solution you'd like

Add an optional boolean flag to the existing `delete_user` methods.

## Describe alternatives you've considered

N/A.

## Additional context

I am happy to add this feature.

**Comment by silentworks** [comment]
This got merged in and is available in the latest release.
