### ISSUE TITLE
When creating a client from tokens purely there's an issue

### ISSUE THREAD

**Issue by mathatan** [supabase/auth-py#537]
# Bug report

## Describe the bug

Trying to create a client with `create_async_client` results in `TypeError: object NoneType can't be used in 'await' expression` errors if the session is not defined before get_session is called with tokens. (or in any case when data is set to `None` before trying to retrieve it)

## To Reproduce

Initialize session with (or similar):

```
self.supabase_client = await create_async_client(
    settings.SUPABASE_URL,
    settings.SUPABASE_KEY,
    options=ClientOptions(
        headers={"Authorization": f"Bearer {self.access_token}"},
        postgrest_client_timeout=10,
        storage_client_timeout=10,
    ),
)

await self.supabase_client.auth.set_session(access_token=self.access_token,  refresh_token=self.refresh_token)
```

Then later call (against the client instance initialized in code above):

```
session = await supabase_client.auth.get_session()
```

## Expected behavior

No thrown errors

## System information

- Python: Python 3.12.3
- MacOS
- Ran in FastApi through `langchain serve`

## Additional context

PR with a fix: https://github.com/supabase-community/auth-py/pull/536

**Comment by silentworks** [comment]
In your example above you are showing you instantiating the client inside a class and then the later call is showing you calling `supabase` directly. I have no idea where this `supabase` is coming from. I can't see any bugs here. Please provide a reproducible example repository.

**Comment by silentworks** [comment]
Closing this out as there was no reply from OP.
