### ISSUE TITLE
Twilio Verify Phone Signup - Error sending confirmation sms: Invalid parameter 'To'

### ISSUE THREAD

**Issue by JeremyBrent** [supabase/auth-py#543]
# Bug report

## Describe the bug

Using Twilio Verify for SMS Phone User Signup produces the error 
`User signup AuthApiError error status: 422, message: Error sending confirmation sms: Invalid parameter 'To': +{number} More information: https://www.twilio.com/docs/errors/60200`

## To Reproduce

```
resp = await supabase.auth.sign_up(
            credentials={'phone': f'+{user.phone}' if '+' not in user.phone else user.phone,
                         'password': user.password,
                         'options': {
                             'data': {
                                 'first_name': user.first_name,
                                 'last_name': user.last_name},
                             'channel': 'sms'
                             }
                         })
```

## System information

- Running FastAPI (0.110.0) Server on Localhost (Mac Sonoma 14.5)
- Supabase Version (2.4.0)

**Comment by silentworks** [comment]
This library itself doesn't append anything to the phone number. The issue is either with your Twilio config or with the auth server (https://github.com/supabase/auth).
