### ISSUE TITLE
Add jwt parameter to the update_user function

### ISSUE THREAD

**Issue by Ashkewww** [supabase/auth-py#563]
# Chore
The update_user() function in async gotrue_client and sync gotrue_client both does not take jwt as a parameter. I was working on supabase and thought this will make it convenient for some use cases. 

##### Synchronous

```
def update_user(self, attributes: UserAttributes) -> UserResponse:
        """
        Updates user data, if there is a logged in user.
        """
        session = self.get_session()
        if not session:
            raise AuthSessionMissingError()
        response = self._request(
            "PUT",
            "user",
            body=attributes,
            jwt=session.access_token,
            xform=parse_user_response,
        )
        session.user = response.user
        self._save_session(session)
        self._notify_all_subscribers("USER_UPDATED", session)
        return response
```

Asynchronous

```
async def update_user(self, attributes: UserAttributes) -> UserResponse:
        """
        Updates user data, if there is a logged in user.
        """
        session = await self.get_session()
        if not session:
            raise AuthSessionMissingError()
        response = await self._request(
            "PUT",
            "user",
            body=attributes,
            jwt=session.access_token,
            xform=parse_user_response,
        )
        session.user = response.user
        await self._save_session(session)
        self._notify_all_subscribers("USER_UPDATED", session)
        return response
```
Right now, update_user() function is taking the jwt from the session and requiring logging in. Just adding a check for the jwt parameter would be enough to get it working. Just like the get_user() function.

**Comment by silentworks** [comment]
This would be incorrect behavior as it doesn't follow the other libraries. The `get_user()` function has this due to legacy code but introducing this change to this method would bring confusion. It's better to create a new client and pass the JWT at the initializer level at this point.
```python
from supabase import Client, create_client
client = create_client(
    url,
    key,
    options=ClientOptions(
        headers={"Authorization": f"Bearer {jwt}"},
    ),
)
client.update_user({...})
```

**Comment by silentworks** [comment]
This deviates from the behavior of all the other client libraries and wouldn't be a change that would be made to the Python library without a consensus from the other libraries.
