### ISSUE TITLE
_remove_session bug causing sign_up to fail

### ISSUE THREAD

**Issue by jpan8866** [supabase/auth-py#630]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using async client's auth.sign_up, it will fail due to _remove_session. Specifically, the line 
```
await self._storage.remove_item(self._storage_key)
```
will error out due to remove_item returning None.

## To Reproduce

Try to use auth.signup with async client

## Screenshots
```Error removing session: object NoneType can't be used in 'await' expression```

## System information

macOS

**Comment by silentworks** [comment]
Please provide a reproducible example repo. I can't replicate this from my end.

**Comment by silentworks** [comment]
OP hasn't replied in over a month so closing this out.
